application: restoringtrentoniw
version: dev
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /GeoSearch/js
  static_dir: GeoSearch/js

- url: /GeoSearch/css
  static_dir: GeoSearch/css

- url: /jquery
  static_dir: jquery

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: '2.5.2'
- name: jinja2
  version: '2.6'